# Generated by Django 5.0.6 on 2024-05-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch_list', '0002_watchlist_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamplatform',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='streamplatform',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
